export const folders = [
  {
    id: 'folder-001',
    name: 'Institute Insights',
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    owner: 'Cap',
    visibility: 'internal',
    tags: ['insight', 'research', 'vector'],
    type: 'insight',
    syncStatus: 'vectorized',
    fileCount: 12,
    purpose: 'Equip saints with divine knowledge via passive learning',
    assignedAgent: 'SaintSal',
  },
  {
    id: 'folder-002',
    name: 'Client Briefs',
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    owner: 'SaintSal',
    visibility: 'client',
    tags: ['brief', 'report', 'pdf'],
    type: 'brief',
    syncStatus: 'idle',
    fileCount: 5,
    purpose: 'Deliver actionable, forward-facing briefings to clients',
    assignedAgent: 'Athena.ai',
  },
  {
    id: 'folder-003',
    name: 'Divine Downloads',
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    owner: 'Athena.ai',
    visibility: 'private',
    tags: ['prophetic', 'strategy', 'mission'],
    type: 'mission',
    syncStatus: 'indexing',
    fileCount: 3,
    purpose: 'Store prophetic insights and executive mission strategy',
    assignedAgent: 'Cap',
  },
]
