export const highlights = [
  {
    id: 'highlight-001',
    fileId: 'file-001',
    user: 'Cap',
    content: 'Passive learning must remain enabled to fulfill the divine indexing mission.',
    tags: ['HACP', 'vector', 'insight'],
    createdAt: new Date().toISOString(),
    page: 3,
    context: 'Institute Brief: Learning Protocols',
    sentiment: 'motivated',
    companion: 'Athena.ai',
  },
  {
    id: 'highlight-002',
    fileId: 'file-002',
    user: 'SaintSal',
    content: 'This valuation logic will empower real estate clients with JP Morgan-level insight.',
    tags: ['valuation', 'real-estate', 'client'],
    createdAt: new Date().toISOString(),
    page: 7,
    context: 'Client Brief: Property ROI',
    sentiment: 'confident',
    companion: 'SaintSal',
  },
  {
    id: 'highlight-003',
    fileId: 'file-003',
    user: 'Athena.ai',
    content: 'Faith-based leadership reduces burnout and builds eternal resilience.',
    tags: ['leadership', 'faith', 'institute'],
    createdAt: new Date().toISOString(),
    page: 12,
    context: 'Devotional Leadership Deck',
    sentiment: 'uplifted',
    companion: 'Athena.ai',
  },
]
